version: 2.1
orbs:
    katalonstudio: katalon/katalonstudio@21.0.0
workflows:
  build:
    jobs:
        - katalonstudio/katjob:
                version: "latest"
                katalon_param: '-browserType="Chrome" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
