version: 2.1
orbs:
    katalonstudio: katalon/katalonstudio@32.0.0

environment:
  KATALON_API_KEY: $KATALON_API_KEY
workflows:
  build:
    jobs:
        - katalonstudio/katjob:
                version: "latest"
                katalon_param: '-browserType="Chrome" -retry=1 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
