ersion: 2.1
orbs:
    katalonstudio: katalon/katalonstudio@25.0.0
workflows:
  build:
    jobs:
        - katalonstudio/katjob:
                version: "latest"
                katalon_param: '-browserType="Chrome" -retry=3 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
          environment:
                KATALON_API_KEY: KATALON_API_KEY
