version: 2.1
orbs:
    katalonstudio: katalon-orb-test/katalonstudio@0.0.26
workflows:
  build:
    jobs:
        - katalonstudio/katjob:
                katalon_param: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
